### ISSUE TITLE
Improve binary filter load time

### ISSUE THREAD

**Issue by subsymbolic** [duckduckgo/bloom_cpp#6]
The bloom filter lookups are fast (nanoseconds rather than milliseconds on ~3million records) however the binary vector load time in `readVectorFromStream` is slow (seconds).

Ideally, we would improve this load time while still keeping the binary small and lookup times fast. This may mean moving the underlying data structure from a bool vector which is challenging to write to file as it doesn't store its elements as a contiguous array.

**Comment by Pascal-So** [comment]
Hi, this sounds like a fun thing to help out with!
1. Does the "help wanted" label mean you're also open for outsiders to contribute or is that directed towards duckduckgo empoyees? I use duckduckgo on all my devices and thought I'd try and give something back by contributing to something for duckduckgo, so this issue here caught my attention.
2. If I were to contribute, my plan would be to first add some benchmarking to the project so we can check if changes actually do something. Is there already some kind of benchmarking in place that I just haven't seen yet? Where did you get those times you're mentioning? If there isn't any benchmarking in place, I'd add some with the "hayai" benchmarking library, which I haven't personally used yet, but looks easy enough. I already started some small experiments which you can find on the benchmark branch in my fork. I guess, once I have a solid benchmarking infrastructure in place it would make sense to first PR that individually, and then later send a second PR when I figure out how to improve `readVectorFromStream`'s performance. Does this sound good to you?
Also feel free to tell me if I'm going about this the wrong way, as I haven't contributed to that many different projects yet.

**Comment by subsymbolic** [comment]
Great to hear that you enjoy using duckduckgo and it's awesome that you are interested in contributing. As for the "help-wanted" label, that's exactly right, it means that we are not actively working on the issue internally and have opened it up to outside collaboration.

We don't currently have any benchmarking in place. That would be a great place to start and your suggestion of submitting it as a separate PR is a good one. I'm not familiar with "hayai" but am open to any lightweight tool that we can easily run with our existing tests.

@klutz you expressed some interest in both working on this issue and benchmarking in the past. Did you have a particular benchmarking tool in mind? Perhaps you two can collaborate on this.

**Comment by gdoubleyew** [comment]
Hi all, I've started working on this issue.

My approach is:
1) Change the <bool> vector to a generic <BlockType> vector where BlockType is char by default.
2) Add the logic to get/set a bit within a BlockType vector.
3) Add a file header to the saved Bloom Filter that includes version number, magic number, and various size parameters such as maxItems, sizeInBits etc. If the magic number isn't present then assume legacy file layout.
4) To load the vector from a file, get the vector.data() pointer and read directly into that memory address.
5) To write the vector to a file, get the vector.data() pointer and write it out directly.

I've got initial code working, but it needs to be cleaned up some and then the timing comparison between the current implementation and the new implementation.

Is it possible to get a development branch for this change?

Grant

**Comment by gdoubleyew** [comment]
Ok, I did some timing on this new implementation and compared to the previous.
Timing is with 3 million entries in bloomfilter, running on a Macbook Pro.

Lookup time:
	new: 2.1 usec
	old: 2.0 usec
Insert time:
	new: 2.8 usec
	old: 2.5 usec
Load time (cumulative all entries):
	new: 0.21 sec
	old: 2.68 sec
Save time (cumulative):
	new: 0.03 sec
	old: 2.27 sec

So load is 10x faster, save is 100x faster, lookup and insert 5-10% slower.

**Comment by gdoubleyew** [comment]
Is this change still needed? Are you guys still around?

**Comment by subsymbolic** [comment]
We are! Please excuse our slow responses, we're all currently on other projects. Many thanks for submitting your PR, it may take us some time to review it but we will get to it in the next few weeks.

**Comment by gdoubleyew** [comment]
Ok great, thanks for the reply, no problem.

**Comment by subsymbolic** [comment]
Removing the "Help Wanted" label as @gdoubleyew has provided a submission that we will use as a guide for future work.
